-- =============================================
-- ADD ADDITIONAL TOPICS
-- Expands the topic catalog with viral, trending, tech, fitness, fashion, travel, food, and business topics
-- =============================================

INSERT INTO public.topics (slug, label, description, is_featured, created_by)
VALUES
  ('viral', 'Viral', 'Content exploding in popularity.', true, NULL),
  ('trending', 'Trending', 'What''s hot right now.', true, NULL),
  ('fyp', 'FYP', 'For You Page algorithm boost.', false, NULL),
  ('foryou', 'ForYou', 'TikTok/Instagram discovery page.', false, NULL),
  ('explore', 'Explore', 'Instagram explore/feed visibility.', false, NULL),
  ('explorepage', 'ExplorePage', 'Reach new audiences on IG.', false, NULL),
  ('viralvideos', 'ViralVideos', 'Videos going massively viral.', true, NULL),
  ('trendingnow', 'TrendingNow', 'Current hot trends.', true, NULL),
  ('viralpost', 'ViralPost', 'Posts blowing up.', false, NULL),
  ('mustsee', 'MustSee', 'Eye-catching must-watch content.', false, NULL),
  ('wow', 'Wow', 'Shocking or amazing moments.', false, NULL),
  ('epic', 'Epic', 'Grand, impressive content.', false, NULL),
  ('mindblown', 'MindBlown', 'Mind-bending facts or reveals.', false, NULL),
  ('lifehack', 'LifeHack', 'Clever everyday shortcuts.', false, NULL),
  ('protip', 'ProTip', 'Professional quick advice.', false, NULL),
  ('hack', 'Hack', 'Smart tricks to save time/money.', false, NULL),
  ('tipsandtricks', 'TipsAndTricks', 'Helpful tips collection.', false, NULL),
  ('dailytips', 'DailyTips', 'Everyday useful advice.', false, NULL),
  ('tech', 'Tech', 'All things technology.', true, NULL),
  ('technology', 'Technology', 'Gadgets and innovations.', false, NULL),
  ('app', 'App', 'Mobile applications.', false, NULL),
  ('mobileapp', 'MobileApp', 'Smartphone apps.', false, NULL),
  ('newapp', 'NewApp', 'Freshly launched applications.', false, NULL),
  ('appdevelopment', 'AppDevelopment', 'Building apps.', false, NULL),
  ('appdeveloper', 'AppDeveloper', 'People who code apps.', false, NULL),
  ('android', 'Android', 'Google''s mobile OS.', false, NULL),
  ('ios', 'iOS', 'Apple''s mobile OS.', false, NULL),
  ('iphone', 'iPhone', 'Apple smartphone.', false, NULL),
  ('androidapp', 'AndroidApp', 'Apps for Android devices.', false, NULL),
  ('appstore', 'AppStore', 'Apple''s app marketplace.', false, NULL),
  ('googleplay', 'GooglePlay', 'Android app store.', false, NULL),
  ('technews', 'TechNews', 'Latest technology updates.', false, NULL),
  ('gadgets', 'Gadgets', 'Cool electronic devices.', false, NULL),
  ('smartphone', 'Smartphone', 'Modern mobile phones.', false, NULL),
  ('artificialintelligence', 'ArtificialIntelligence', 'Machines thinking smart.', false, NULL),
  ('machinelearning', 'MachineLearning', 'AI that learns from data.', false, NULL),
  ('coding', 'Coding', 'Writing code.', false, NULL),
  ('programming', 'Programming', 'Software creation.', false, NULL),
  ('developer', 'Developer', 'Software coder.', false, NULL),
  ('software', 'Software', 'Programs and apps.', false, NULL),
  ('techstartup', 'TechStartup', 'Technology-based new business.', false, NULL),
  ('innovation', 'Innovation', 'New ideas and inventions.', false, NULL),
  ('futuretech', 'FutureTech', 'Upcoming technology.', false, NULL),
  ('cybersecurity', 'CyberSecurity', 'Protecting against hackers.', false, NULL),
  ('blockchain', 'Blockchain', 'Decentralized ledger tech.', false, NULL),
  ('crypto', 'Crypto', 'Cryptocurrency.', false, NULL),
  ('metaverse', 'Metaverse', 'Virtual worlds.', false, NULL),
  ('ar', 'AR', 'Augmented Reality.', false, NULL),
  ('vr', 'VR', 'Virtual Reality.', false, NULL),
  ('augmentedreality', 'AugmentedReality', 'Overlay digital on real world.', false, NULL),
  ('virtualreality', 'VirtualReality', 'Fully immersive digital worlds.', false, NULL),
  ('5g', '5G', 'Fast mobile internet.', false, NULL),
  ('iot', 'IoT', 'Internet of Things.', false, NULL),
  ('internetofthings', 'InternetOfThings', 'Connected smart devices.', false, NULL),
  ('cloudcomputing', 'CloudComputing', 'Online data storage.', false, NULL),
  ('bigdata', 'BigData', 'Massive data analysis.', false, NULL),
  ('fitness', 'Fitness', 'Physical exercise.', false, NULL),
  ('workout', 'Workout', 'Exercise sessions.', false, NULL),
  ('gym', 'Gym', 'Gym culture and training.', false, NULL),
  ('fitnessmotivation', 'FitnessMotivation', 'Inspiring gym content.', false, NULL),
  ('health', 'Health', 'Overall well-being.', false, NULL),
  ('healthylifestyle', 'HealthyLifestyle', 'Living healthy daily.', false, NULL),
  ('fitlife', 'FitLife', 'Lifestyle of fitness.', false, NULL),
  ('gymlife', 'GymLife', 'Dedicated gym goers.', false, NULL),
  ('bodybuilding', 'Bodybuilding', 'Building muscle mass.', false, NULL),
  ('weightloss', 'WeightLoss', 'Losing body fat.', false, NULL),
  ('fatloss', 'FatLoss', 'Targeted fat reduction.', false, NULL),
  ('musclegain', 'MuscleGain', 'Growing muscle.', false, NULL),
  ('fitfam', 'FitFam', 'Fitness community.', false, NULL),
  ('fitnessjourney', 'FitnessJourney', 'Personal progress.', false, NULL),
  ('homeworkout', 'HomeWorkout', 'Exercise at home.', false, NULL),
  ('cardio', 'Cardio', 'Heart-pumping workouts.', false, NULL),
  ('hiit', 'HIIT', 'High-Intensity Interval Training.', false, NULL),
  ('yoga', 'Yoga', 'Mind-body practice.', false, NULL),
  ('meditation', 'Meditation', 'Mindfulness and calm.', false, NULL),
  ('mentalhealth', 'MentalHealth', 'Emotional well-being.', false, NULL),
  ('nutrition', 'Nutrition', 'Food and diet science.', false, NULL),
  ('healthyeating', 'HealthyEating', 'Clean food choices.', false, NULL),
  ('mealprep', 'MealPrep', 'Pre-making meals.', false, NULL),
  ('keto', 'Keto', 'Ketogenic low-carb diet.', false, NULL),
  ('vegan', 'Vegan', 'Plant-based no animal products.', false, NULL),
  ('plantbased', 'PlantBased', 'Mostly plants diet.', false, NULL),
  ('running', 'Running', 'Jogging and marathons.', false, NULL),
  ('marathon', 'Marathon', 'Long-distance running.', false, NULL),
  ('crossfit', 'CrossFit', 'Intense functional training.', false, NULL),
  ('pilates', 'Pilates', 'Core strength exercises.', false, NULL),
  ('strengthtraining', 'StrengthTraining', 'Lifting for power.', false, NULL),
  ('fashion', 'Fashion', 'Clothing trends.', false, NULL),
  ('style', 'Style', 'Personal fashion sense.', false, NULL),
  ('ootd', 'OOTD', 'Outfit Of The Day.', false, NULL),
  ('outfitoftheday', 'OutfitOfTheDay', 'Daily outfit posts.', false, NULL),
  ('fashionstyle', 'FashionStyle', 'Trendy looks.', false, NULL),
  ('beauty', 'Beauty', 'Makeup and skincare.', false, NULL),
  ('makeup', 'Makeup', 'Cosmetics application.', false, NULL),
  ('skincare', 'Skincare', 'Skin health routines.', false, NULL),
  ('haircare', 'Haircare', 'Hair maintenance.', false, NULL),
  ('fashionblogger', 'FashionBlogger', 'Fashion influencers.', false, NULL),
  ('streetstyle', 'StreetStyle', 'Casual urban looks.', false, NULL),
  ('luxuryfashion', 'LuxuryFashion', 'High-end designer brands.', false, NULL),
  ('vintage', 'Vintage', 'Retro clothing.', false, NULL),
  ('trendy', 'Trendy', 'Current hot styles.', false, NULL),
  ('chic', 'Chic', 'Elegant and stylish.', false, NULL),
  ('glam', 'Glam', 'Glamorous looks.', false, NULL),
  ('model', 'Model', 'Fashion modeling.', false, NULL),
  ('fashioninspo', 'FashionInspo', 'Outfit inspiration.', false, NULL),
  ('beautytips', 'BeautyTips', 'Makeup/skincare advice.', false, NULL),
  ('makeuptutorial', 'MakeupTutorial', 'Step-by-step makeup.', false, NULL),
  ('nails', 'Nails', 'Nail art and care.', false, NULL),
  ('hairstyle', 'HairStyle', 'Hairstyling ideas.', false, NULL),
  ('fashionweek', 'FashionWeek', 'Major fashion events.', false, NULL),
  ('designer', 'Designer', 'Clothing designers.', false, NULL),
  ('couture', 'Couture', 'Custom high fashion.', false, NULL),
  ('travel', 'Travel', 'Exploring the world.', false, NULL),
  ('wanderlust', 'Wanderlust', 'Strong desire to travel.', false, NULL),
  ('travelgram', 'TravelGram', 'Instagram travel posts.', false, NULL),
  ('adventure', 'Adventure', 'Thrilling experiences.', false, NULL),
  ('vacation', 'Vacation', 'Holiday trips.', false, NULL),
  ('travelphotography', 'TravelPhotography', 'Scenic travel pics.', false, NULL),
  ('nature', 'Nature', 'Outdoor natural beauty.', false, NULL),
  ('beach', 'Beach', 'Sandy shores and ocean.', false, NULL),
  ('mountains', 'Mountains', 'Hiking and peaks.', false, NULL),
  ('hiking', 'Hiking', 'Trail walking.', false, NULL),
  ('roadtrip', 'RoadTrip', 'Car journeys.', false, NULL),
  ('backpacking', 'Backpacking', 'Budget travel.', false, NULL),
  ('travelblogger', 'TravelBlogger', 'Travel influencers.', false, NULL),
  ('tourism', 'Tourism', 'Visiting attractions.', false, NULL),
  ('paradise', 'Paradise', 'Dream destinations.', false, NULL),
  ('sunset', 'Sunset', 'Evening sky photos.', false, NULL),
  ('citylife', 'CityLife', 'Urban exploration.', false, NULL),
  ('europe', 'Europe', 'European travel.', false, NULL),
  ('asia', 'Asia', 'Asian destinations.', false, NULL),
  ('usa', 'USA', 'American travel spots.', false, NULL),
  ('travelgoals', 'TravelGoals', 'Dream trips.', false, NULL),
  ('bucketlist', 'BucketList', 'Must-do experiences.', false, NULL),
  ('globetrotter', 'GlobeTrotter', 'World traveler.', false, NULL),
  ('solotravel', 'SoloTravel', 'Traveling alone.', false, NULL),
  ('familytravel', 'FamilyTravel', 'Trips with kids.', false, NULL),
  ('food', 'Food', 'Delicious eats.', false, NULL),
  ('foodie', 'Foodie', 'Food lovers.', false, NULL),
  ('foodporn', 'FoodPorn', 'Mouthwatering food pics.', false, NULL),
  ('instafood', 'InstaFood', 'Instagram-worthy meals.', false, NULL),
  ('delicious', 'Delicious', 'Tasty food.', false, NULL),
  ('yummy', 'Yummy', 'Super appetizing.', false, NULL),
  ('cooking', 'Cooking', 'Preparing food.', false, NULL),
  ('recipe', 'Recipe', 'Food instructions.', false, NULL),
  ('homemade', 'Homemade', 'Made at home.', false, NULL),
  ('foodblog', 'FoodBlog', 'Food influencers.', false, NULL),
  ('healthyfood', 'HealthyFood', 'Nutritious meals.', false, NULL),
  ('veganfood', 'VeganFood', 'Plant-based dishes.', false, NULL),
  ('dessert', 'Dessert', 'Sweet treats.', false, NULL),
  ('baking', 'Baking', 'Oven goodies.', false, NULL),
  ('coffee', 'Coffee', 'Coffee culture.', false, NULL),
  ('breakfast', 'Breakfast', 'Morning meals.', false, NULL),
  ('lunch', 'Lunch', 'Midday food.', false, NULL),
  ('dinner', 'Dinner', 'Evening meals.', false, NULL),
  ('pizza', 'Pizza', 'Everyone''s favorite.', false, NULL),
  ('sushi', 'Sushi', 'Japanese raw fish rolls.', false, NULL),
  ('tacos', 'Tacos', 'Mexican street food.', false, NULL),
  ('burger', 'Burger', 'Juicy hamburgers.', false, NULL),
  ('foodphotography', 'FoodPhotography', 'Beautiful food shots.', false, NULL),
  ('chef', 'Chef', 'Professional cooks.', false, NULL),
  ('kitchen', 'Kitchen', 'Cooking space.', false, NULL),
  ('mealideas', 'MealIdeas', 'What to eat today.', false, NULL),
  ('entrepreneur', 'Entrepreneur', 'Business starters.', false, NULL),
  ('entrepreneurship', 'Entrepreneurship', 'Starting companies.', false, NULL),
  ('businessowner', 'BusinessOwner', 'Own your own company.', false, NULL),
  ('hustle', 'Hustle', 'Hard work grind.', false, NULL),
  ('success', 'Success', 'Achieving goals.', false, NULL),
  ('motivation', 'Motivation', 'Drive to succeed.', false, NULL),
  ('inspiration', 'Inspiration', 'Ideas that spark.', false, NULL),
  ('money', 'Money', 'Wealth and finance.', false, NULL),
  ('stocks', 'Stocks', 'Stock market.', false, NULL),
  ('cryptocurrency', 'CryptoCurrency', 'Digital money.', false, NULL),
  ('sidehustle', 'SideHustle', 'Extra income streams.', false, NULL),
  ('passiveincome', 'PassiveIncome', 'Money while sleeping.', false, NULL),
  ('digitalmarketing', 'DigitalMarketing', 'Online promotion.', false, NULL),
  ('seo', 'SEO', 'Search engine optimization.', false, NULL),
  ('socialmediamarketing', 'SocialMediaMarketing', 'Social ads.', false, NULL),
  ('brand', 'Brand', 'Company identity.', false, NULL),
  ('goals', 'Goals', 'Targets to hit.', false, NULL),
  ('productivity', 'Productivity', 'Getting more done.', false, NULL),
  ('timemanagement', 'TimeManagement', 'Organizing your day.', false, NULL)
ON CONFLICT (slug) DO NOTHING;

