-- =============================================
-- ADD GAMING, LIFESTYLE, AND DEEP NICHE TOPICS
-- Expands topic catalog with gaming, photography, music, lifestyle, memes, baking, parenting, mental health, and more
-- =============================================

INSERT INTO public.topics (slug, label, description, is_featured, created_by)
VALUES
  -- Gaming
  ('gaming', 'Gaming', 'Video games and gaming culture.', true, NULL),
  ('gamer', 'Gamer', 'People who love gaming.', false, NULL),
  ('videogames', 'VideoGames', 'All types of games.', false, NULL),
  ('playstation', 'PlayStation', 'Sony consoles.', false, NULL),
  ('ps5', 'PS5', 'Latest PlayStation.', false, NULL),
  ('xbox', 'Xbox', 'Microsoft consoles.', false, NULL),
  ('xboxseriesx', 'XboxSeriesX', 'Current Xbox.', false, NULL),
  ('nintendo', 'Nintendo', 'Nintendo gaming.', false, NULL),
  ('switch', 'Switch', 'Nintendo Switch console.', false, NULL),
  ('pcgaming', 'PCGaming', 'Gaming on computers.', false, NULL),
  ('mobilegaming', 'MobileGaming', 'Games on phones.', false, NULL),
  ('fortnite', 'Fortnite', 'Popular battle royale.', false, NULL),
  ('minecraft', 'Minecraft', 'Block-building game.', false, NULL),
  ('callofduty', 'CallOfDuty', 'Shooter franchise.', false, NULL),
  ('cod', 'COD', 'Call of Duty short.', false, NULL),
  ('warzone', 'Warzone', 'COD battle royale.', false, NULL),
  ('amongus', 'AmongUs', 'Social deduction game.', false, NULL),
  ('roblox', 'Roblox', 'User-created games platform.', false, NULL),
  ('esports', 'Esports', 'Competitive gaming.', false, NULL),
  ('streamer', 'Streamer', 'Live game broadcasters.', false, NULL),
  ('twitch', 'Twitch', 'Main streaming platform.', false, NULL),
  ('twitchstreamer', 'TwitchStreamer', 'Twitch broadcasters.', false, NULL),
  ('youtubegaming', 'YouTubeGaming', 'Gaming on YouTube.', false, NULL),
  ('gameplay', 'Gameplay', 'Recorded or live play.', false, NULL),
  ('levelup', 'LevelUp', 'Improving in games.', false, NULL),
  ('gamergirl', 'GamerGirl', 'Female gamers.', false, NULL),
  ('gamerboy', 'GamerBoy', 'Male gamers.', false, NULL),
  ('retrogaming', 'RetroGaming', 'Old-school games.', false, NULL),
  ('indiegames', 'IndieGames', 'Independent developer games.', false, NULL),
  ('rpg', 'RPG', 'Role-playing games.', false, NULL),
  ('fps', 'FPS', 'First-person shooter.', false, NULL),
  ('mmo', 'MMO', 'Massive multiplayer online.', false, NULL),
  
  -- Photography & Art
  ('photography', 'Photography', 'Capturing images.', false, NULL),
  ('photooftheday', 'PhotoOfTheDay', 'Daily best photo.', false, NULL),
  ('picoftheday', 'PicOfTheDay', 'Picture of the day.', false, NULL),
  ('art', 'Art', 'Creative works.', false, NULL),
  ('artist', 'Artist', 'Creators of art.', false, NULL),
  ('drawing', 'Drawing', 'Pencil or digital sketches.', false, NULL),
  ('painting', 'Painting', 'Traditional or digital paint.', false, NULL),
  ('digitalart', 'DigitalArt', 'Art made on computers.', false, NULL),
  ('illustration', 'Illustration', 'Illustrated artwork.', false, NULL),
  ('creative', 'Creative', 'Being artistic.', false, NULL),
  ('graphicdesign', 'GraphicDesign', 'Logos, posters, UI.', false, NULL),
  ('instaart', 'InstaArt', 'Art for Instagram.', false, NULL),
  ('photo', 'Photo', 'General photography.', false, NULL),
  ('camera', 'Camera', 'Photography gear.', false, NULL),
  ('landscape', 'Landscape', 'Nature and scenery shots.', false, NULL),
  ('portrait', 'Portrait', 'People photos.', false, NULL),
  ('blackandwhite', 'BlackAndWhite', 'Monochrome photography.', false, NULL),
  ('aesthetic', 'Aesthetic', 'Visually pleasing style.', false, NULL),
  ('visualart', 'VisualArt', 'Art you can see.', false, NULL),
  ('streetphotography', 'StreetPhotography', 'Urban candid shots.', false, NULL),
  ('macrophotography', 'MacroPhotography', 'Extreme close-ups.', false, NULL),
  ('wildlifephotography', 'WildlifePhotography', 'Animals in nature.', false, NULL),
  ('dronephotography', 'DronePhotography', 'Aerial shots.', false, NULL),
  
  -- Music
  ('song', 'Song', 'Individual tracks.', false, NULL),
  ('newmusic', 'NewMusic', 'Fresh releases.', false, NULL),
  ('dance', 'Dance', 'Dancing content.', false, NULL),
  ('dancing', 'Dancing', 'People dancing.', false, NULL),
  ('musician', 'Musician', 'People who play music.', false, NULL),
  ('singer', 'Singer', 'Vocal artists.', false, NULL),
  ('guitar', 'Guitar', 'Guitar players.', false, NULL),
  ('piano', 'Piano', 'Piano players.', false, NULL),
  ('hiphop', 'HipHop', 'Hip-hop genre.', false, NULL),
  ('rap', 'Rap', 'Rap music.', false, NULL),
  ('popmusic', 'PopMusic', 'Pop genre.', false, NULL),
  ('rockmusic', 'RockMusic', 'Rock genre.', false, NULL),
  ('edm', 'EDM', 'Electronic dance music.', false, NULL),
  ('dj', 'DJ', 'Disc jockeys.', false, NULL),
  ('concert', 'Concert', 'Live shows.', false, NULL),
  ('livemusic', 'LiveMusic', 'Performances.', false, NULL),
  ('musicvideo', 'MusicVideo', 'Official videos.', false, NULL),
  ('coversong', 'CoverSong', 'Remakes of songs.', false, NULL),
  ('beat', 'Beat', 'Instrumentals.', false, NULL),
  ('lyrics', 'Lyrics', 'Song words.', false, NULL),
  ('indiemusic', 'IndieMusic', 'Independent music.', false, NULL),
  ('jazz', 'Jazz', 'Jazz genre.', false, NULL),
  ('classicalmusic', 'ClassicalMusic', 'Orchestral music.', false, NULL),
  ('countrymusic', 'CountryMusic', 'Country genre.', false, NULL),
  ('reggae', 'Reggae', 'Reggae music.', false, NULL),
  ('kpop', 'KPOP', 'Korean pop.', false, NULL),
  ('bts', 'BTS', 'Famous K-pop group.', false, NULL),
  ('blackpink', 'Blackpink', 'K-pop girl group.', false, NULL),
  
  -- Lifestyle
  ('lifestyle', 'Lifestyle', 'Everyday living.', false, NULL),
  ('dailylife', 'DailyLife', 'Normal day posts.', false, NULL),
  ('morningroutine', 'MorningRoutine', 'Start of day habits.', false, NULL),
  ('nightroutine', 'NightRoutine', 'Wind-down habits.', false, NULL),
  ('selfcare', 'SelfCare', 'Taking care of yourself.', false, NULL),
  ('selflove', 'SelfLove', 'Loving yourself.', false, NULL),
  ('grateful', 'Grateful', 'Being thankful.', false, NULL),
  ('positivevibes', 'PositiveVibes', 'Good energy.', false, NULL),
  ('goodvibes', 'GoodVibes', 'Happy feelings.', false, NULL),
  ('happiness', 'Happiness', 'Joyful content.', false, NULL),
  ('family', 'Family', 'Family moments.', false, NULL),
  ('friends', 'Friends', 'Friendship posts.', false, NULL),
  ('relationship', 'Relationship', 'Couple content.', false, NULL),
  ('couplegoals', 'CoupleGoals', 'Ideal relationships.', false, NULL),
  ('pet', 'Pet', 'Animals as pets.', false, NULL),
  ('dog', 'Dog', 'Dogs.', false, NULL),
  ('cat', 'Cat', 'Cats.', false, NULL),
  ('doglover', 'DogLover', 'Dog enthusiasts.', false, NULL),
  ('catlover', 'CatLover', 'Cat enthusiasts.', false, NULL),
  ('homedecor', 'HomeDecor', 'House styling.', false, NULL),
  ('interiordesign', 'InteriorDesign', 'Professional decor.', false, NULL),
  ('minimalism', 'Minimalism', 'Simple living.', false, NULL),
  ('organization', 'Organization', 'Tidying up.', false, NULL),
  ('productivityhacks', 'ProductivityHacks', 'Efficiency tips.', false, NULL),
  
  -- Memes & Humor
  ('meme', 'Meme', 'Single meme image.', false, NULL),
  ('memes', 'Memes', 'Collection of memes.', false, NULL),
  ('funny', 'Funny', 'Humorous content.', false, NULL),
  ('lol', 'LOL', 'Laugh out loud.', false, NULL),
  ('humor', 'Humor', 'Comedy.', false, NULL),
  ('comedy', 'Comedy', 'Funny skits.', false, NULL),
  ('jokes', 'Jokes', 'Short jokes.', false, NULL),
  ('relatable', 'Relatable', 'Things everyone understands.', false, NULL),
  ('savage', 'Savage', 'Brutally honest humor.', false, NULL),
  ('dankmemes', 'DankMemes', 'High-quality weird memes.', false, NULL),
  ('funnyvideos', 'FunnyVideos', 'Hilarious clips.', false, NULL),
  ('memepage', 'MemePage', 'Meme accounts.', false, NULL),
  ('wholesomememes', 'WholesomeMemes', 'Feel-good memes.', false, NULL),
  
  -- Motivation & Quotes
  ('quote', 'Quote', 'Short quotes.', false, NULL),
  ('quotes', 'Quotes', 'Quote collections.', false, NULL),
  ('successquotes', 'SuccessQuotes', 'Quotes about winning.', false, NULL),
  ('lifequotes', 'LifeQuotes', 'Deep life sayings.', false, NULL),
  ('dreambig', 'DreamBig', 'Aim high.', false, NULL),
  ('nevergiveup', 'NeverGiveUp', 'Persistence.', false, NULL),
  ('hustlehard', 'HustleHard', 'Work ethic.', false, NULL),
  ('bossup', 'BossUp', 'Level up your life.', false, NULL),
  ('believeinyourself', 'BelieveInYourself', 'Self-confidence.', false, NULL),
  ('wintheday', 'WinTheDay', 'Daily motivation.', false, NULL),
  
  -- Baking Deep
  ('baker', 'Baker', 'Home or pro baker.', false, NULL),
  ('cake', 'Cake', 'Cakes of all kinds.', false, NULL),
  ('cupcakes', 'Cupcakes', 'Small cakes.', false, NULL),
  ('cookies', 'Cookies', 'Baked cookies.', false, NULL),
  ('bread', 'Bread', 'Homemade bread.', false, NULL),
  ('pastry', 'Pastry', 'Flaky pastries.', false, NULL),
  ('desserttable', 'DessertTable', 'Dessert displays.', false, NULL),
  ('cakedecorating', 'CakeDecorating', 'Icing and fondant art.', false, NULL),
  ('sourdough', 'Sourdough', 'Sourdough bread trend.', false, NULL),
  ('glutenfreebaking', 'GlutenFreeBaking', 'No-gluten recipes.', false, NULL),
  ('veganbaking', 'VeganBaking', 'Plant-based baking.', false, NULL),
  
  -- Cooking Sub-niches
  ('grilling', 'Grilling', 'BBQ and grilling.', false, NULL),
  ('barbecue', 'Barbecue', 'Smoked meats.', false, NULL),
  ('airfryer', 'AirFryer', 'Air fryer recipes.', false, NULL),
  ('instantpot', 'InstantPot', 'Pressure cooker meals.', false, NULL),
  ('slowcooker', 'SlowCooker', 'Crockpot cooking.', false, NULL),
  ('onepanmeals', 'OnePanMeals', 'Easy cleanup recipes.', false, NULL),
  ('30minutemeals', '30MinuteMeals', 'Quick dinners.', false, NULL),
  ('budgetmeals', 'BudgetMeals', 'Cheap eating.', false, NULL),
  ('gourmet', 'Gourmet', 'Fancy cooking.', false, NULL),
  ('streetfood', 'StreetFood', 'Global street eats.', false, NULL),
  ('italianfood', 'ItalianFood', 'Pasta and pizza.', false, NULL),
  ('mexicanfood', 'MexicanFood', 'Tacos, enchiladas.', false, NULL),
  ('indianfood', 'IndianFood', 'Curries and naan.', false, NULL),
  ('japanesefood', 'JapaneseFood', 'Beyond sushi.', false, NULL),
  ('chinesefood', 'ChineseFood', 'Stir-fry and dim sum.', false, NULL),
  ('thaifood', 'ThaiFood', 'Spicy Thai dishes.', false, NULL),
  ('koreanfood', 'KoreanFood', 'Kimchi and BBQ.', false, NULL),
  
  -- Drinks
  ('cocktails', 'Cocktails', 'Mixed alcoholic drinks.', false, NULL),
  ('mocktails', 'Mocktails', 'Non-alcoholic cocktails.', false, NULL),
  ('smoothiebowl', 'SmoothieBowl', 'Thick smoothie art.', false, NULL),
  ('juicing', 'Juicing', 'Fresh juices.', false, NULL),
  ('tealover', 'TeaLover', 'Tea enthusiasts.', false, NULL),
  ('wine', 'Wine', 'Wine culture.', false, NULL),
  ('craftbeer', 'CraftBeer', 'Microbrew beers.', false, NULL),
  ('latteart', 'LatteArt', 'Coffee foam designs.', false, NULL),
  
  -- Parenting & Family
  ('momlife', 'MomLife', 'Motherhood realities.', false, NULL),
  ('dadlife', 'DadLife', 'Fatherhood.', false, NULL),
  ('parenting', 'Parenting', 'Raising kids.', false, NULL),
  ('toddlerlife', 'ToddlerLife', 'Ages 1-3 chaos.', false, NULL),
  ('newborn', 'Newborn', 'Baby first months.', false, NULL),
  ('pregnant', 'Pregnant', 'Pregnancy journey.', false, NULL),
  ('babybump', 'BabyBump', 'Pregnant belly pics.', false, NULL),
  ('breastfeeding', 'Breastfeeding', 'Nursing moms.', false, NULL),
  ('babyfashion', 'BabyFashion', 'Cute baby clothes.', false, NULL),
  ('kidsactivities', 'KidsActivities', 'Fun for children.', false, NULL),
  ('homeschooling', 'Homeschooling', 'Home education.', false, NULL),
  
  -- Wedding & Events
  ('weddingplanning', 'WeddingPlanning', 'Organizing weddings.', false, NULL),
  ('bridetobe', 'BrideToBe', 'Engaged women.', false, NULL),
  ('weddingdress', 'WeddingDress', 'Bridal gowns.', false, NULL),
  ('weddingphotography', 'WeddingPhotography', 'Wedding photos.', false, NULL),
  ('engagementring', 'EngagementRing', 'Proposal rings.', false, NULL),
  ('bachelorette', 'Bachelorette', 'Pre-wedding parties.', false, NULL),
  ('honeymoon', 'Honeymoon', 'Post-wedding trips.', false, NULL),
  
  -- Mental Health Deep
  ('anxietyrelief', 'AnxietyRelief', 'Calming anxiety.', false, NULL),
  ('depressionawareness', 'DepressionAwareness', 'Mental health talks.', false, NULL),
  ('therapyworks', 'TherapyWorks', 'Benefits of therapy.', false, NULL),
  ('mindfulnessmeditation', 'MindfulnessMeditation', 'Present moment focus.', false, NULL),
  ('journalprompts', 'JournalPrompts', 'Writing for mental health.', false, NULL),
  ('affirmationsdaily', 'AffirmationsDaily', 'Positive statements.', false, NULL),
  
  -- Body Positivity & Fashion Sub
  ('bodypositive', 'BodyPositive', 'All bodies beautiful.', false, NULL),
  ('plussizefashion', 'PlusSizeFashion', 'Curvy clothing.', false, NULL),
  ('petitefashion', 'PetiteFashion', 'Short girl style.', false, NULL),
  ('tallgirlproblems', 'TallGirlProblems', 'Tall women fashion.', false, NULL),
  ('modestfashion', 'ModestFashion', 'Covered styling.', false, NULL),
  ('bohostyle', 'BohoStyle', 'Bohemian looks.', false, NULL),
  ('y2kfashion', 'Y2KFashion', '2000s revival.', false, NULL),
  ('cottagecore', 'Cottagecore', 'Romantic rural aesthetic.', false, NULL),
  ('darkacademia', 'DarkAcademia', 'Scholarly gothic vibe.', false, NULL),
  
  -- Skincare Deep
  ('koreanskincare', 'KoreanSkincare', '10-step routine.', false, NULL),
  ('glassskin', 'GlassSkin', 'Dewy flawless look.', false, NULL),
  ('acnetreatment', 'AcneTreatment', 'Fighting pimples.', false, NULL),
  ('antiagingskincare', 'AntiAgingSkincare', 'Wrinkle prevention.', false, NULL),
  ('cleanbeauty', 'CleanBeauty', 'Natural products.', false, NULL),
  ('crueltyfree', 'CrueltyFree', 'No animal testing.', false, NULL),
  
  -- Makeup Sub
  ('makeuplooks', 'MakeupLooks', 'Full face ideas.', false, NULL),
  ('nomakeupmakeup', 'NoMakeupMakeup', 'Natural enhancement.', false, NULL),
  ('glammakeup', 'GlamMakeup', 'Full beat.', false, NULL),
  ('sfxmakeup', 'SFXMakeup', 'Special effects.', false, NULL),
  ('eyeshadowlooks', 'EyeshadowLooks', 'Eye makeup focus.', false, NULL),
  ('lipstickaddict', 'LipstickAddict', 'Lip color lovers.', false, NULL),
  
  -- Fitness Sub-niches
  ('powerlifting', 'Powerlifting', 'Heavy strength training.', false, NULL),
  ('bodyweightworkout', 'BodyweightWorkout', 'No equipment needed.', false, NULL),
  ('calisthenics', 'Calisthenics', 'Bodyweight strength.', false, NULL),
  ('marathontraining', 'MarathonTraining', 'Long run prep.', false, NULL),
  ('triathlon', 'Triathlon', 'Swim bike run.', false, NULL),
  ('spinclass', 'SpinClass', 'Indoor cycling.', false, NULL),
  ('barre', 'Barre', 'Ballet-inspired workout.', false, NULL),
  ('zumba', 'Zumba', 'Dance fitness.', false, NULL),
  ('kickboxing', 'Kickboxing', 'Martial arts cardio.', false, NULL),
  
  -- Travel Sub-niches
  ('solofemaletravel', 'SoloFemaleTravel', 'Women traveling alone.', false, NULL),
  ('luxurytravel', 'LuxuryTravel', 'High-end vacations.', false, NULL),
  ('budgettravel', 'BudgetTravel', 'Cheap trips.', false, NULL),
  ('digitalnomadlife', 'DigitalNomadLife', 'Work while traveling.', false, NULL),
  ('vanlife', 'VanLife', 'Living in vans.', false, NULL),
  ('hostellife', 'HostelLife', 'Backpacker hostels.', false, NULL),
  ('cruise', 'Cruise', 'Ship vacations.', false, NULL),
  ('safari', 'Safari', 'African wildlife trips.', false, NULL),
  ('skitrip', 'SkiTrip', 'Snow sports.', false, NULL),
  ('islandhopping', 'IslandHopping', 'Multiple islands.', false, NULL),
  
  -- Cars & Automotive Deep
  ('carporn', 'Carporn', 'Beautiful car photos.', false, NULL),
  ('jdm', 'JDM', 'Japanese domestic market cars.', false, NULL),
  ('musclecars', 'MuscleCars', 'American power.', false, NULL),
  ('supercars', 'Supercars', 'Lamborghini, Ferrari.', false, NULL),
  ('hypercars', 'Hypercars', 'Million-dollar cars.', false, NULL),
  ('electricvehicles', 'ElectricVehicles', 'EVs like Tesla.', false, NULL),
  ('carmeet', 'CarMeet', 'Car enthusiast gatherings.', false, NULL),
  ('drifting', 'Drifting', 'Slide driving.', false, NULL),
  ('offroading', 'OffRoading', '4x4 adventures.', false, NULL),
  ('classiccars', 'ClassicCars', 'Vintage vehicles.', false, NULL),
  
  -- Cryptocurrency Deep
  ('bitcoin', 'Bitcoin', 'Original crypto.', false, NULL),
  ('ethereum', 'Ethereum', 'Smart contracts.', false, NULL),
  ('altcoins', 'Altcoins', 'Other cryptocurrencies.', false, NULL),
  ('nfts', 'NFTs', 'Non-fungible tokens.', false, NULL),
  ('defi', 'DeFi', 'Decentralized finance.', false, NULL),
  ('cryptotrading', 'CryptoTrading', 'Buying/selling crypto.', false, NULL),
  ('hodl', 'HODL', 'Hold on for dear life.', false, NULL),
  ('moon', 'Moon', 'Price going up.', false, NULL),
  ('web3wallet', 'Web3Wallet', 'Crypto wallets.', false, NULL),
  
  -- Investing & Finance
  ('stockmarket', 'StockMarket', 'Trading stocks.', false, NULL),
  ('daytrading', 'DayTrading', 'Same-day trades.', false, NULL),
  ('swingtrading', 'SwingTrading', 'Few days/weeks.', false, NULL),
  ('valueinvesting', 'ValueInvesting', 'Warren Buffett style.', false, NULL),
  ('dividendstocks', 'DividendStocks', 'Income stocks.', false, NULL),
  ('realestateinvesting', 'RealEstateInvesting', 'Property flips/rentals.', false, NULL),
  ('fire', 'FIRE', 'Financial independence retire early.', false, NULL),
  ('sidehustles', 'SideHustles', 'Extra money ideas.', false, NULL),
  
  -- Books & Reading
  ('bookstagram', 'Bookstagram', 'Book photos.', false, NULL),
  ('booktok', 'BookTok', 'TikTok books.', false, NULL),
  ('bookreview', 'BookReview', 'Honest opinions.', false, NULL),
  ('currentlyreading', 'CurrentlyReading', 'What you''re reading now.', false, NULL),
  ('bookhaul', 'BookHaul', 'New book buys.', false, NULL),
  ('fantasybooks', 'FantasyBooks', 'Magic worlds.', false, NULL),
  ('romancebooks', 'RomanceBooks', 'Love stories.', false, NULL),
  ('thrillerbooks', 'ThrillerBooks', 'Suspense.', false, NULL),
  ('selfhelpbooks', 'SelfHelpBooks', 'Personal growth.', false, NULL),
  
  -- Sustainability & Eco
  ('zerowasteliving', 'ZeroWasteLiving', 'No trash lifestyle.', false, NULL),
  ('plasticfree', 'PlasticFree', 'Avoiding plastic.', false, NULL),
  ('veganism', 'Veganism', 'Ethical no animal products.', false, NULL),
  ('climateaction', 'ClimateAction', 'Fighting climate change.', false, NULL),
  ('rewilding', 'Rewilding', 'Restoring nature.', false, NULL),
  ('permaculture', 'Permaculture', 'Sustainable farming.', false, NULL),
  
  -- Pets Deep
  ('dogtraining', 'DogTraining', 'Teaching dogs.', false, NULL),
  ('puppylove', 'PuppyLove', 'Baby dogs.', false, NULL),
  ('catvideos', 'CatVideos', 'Funny cats.', false, NULL),
  ('rescuedog', 'RescueDog', 'Adopted dogs.', false, NULL),
  ('exoticpets', 'ExoticPets', 'Unusual animals.', false, NULL),
  ('aquarium', 'Aquarium', 'Fish tanks.', false, NULL),
  ('reptilekeeper', 'ReptileKeeper', 'Snakes, lizards.', false, NULL),
  
  -- Holidays & Seasonal Deep
  ('christmasdecor', 'ChristmasDecor', 'Holiday home styling.', false, NULL),
  ('halloweencostume', 'HalloweenCostume', 'Spooky outfits.', false, NULL),
  ('pumpkinspice', 'PumpkinSpice', 'Fall flavor.', false, NULL),
  ('summervibes', 'SummerVibes', 'Beach season.', false, NULL),
  ('cozyseason', 'CozySeason', 'Fall/winter comfort.', false, NULL),
  ('springcleaning', 'SpringCleaning', 'Fresh start.', false, NULL),
  
  -- ASMR & Relax
  ('asmr', 'ASMR', 'Tingles sounds.', false, NULL),
  ('whispering', 'Whispering', 'Soft speaking.', false, NULL),
  ('tapping', 'Tapping', 'Finger tapping sounds.', false, NULL),
  ('roleplay', 'Roleplay', 'ASMR scenarios.', false, NULL),
  ('sleepaid', 'SleepAid', 'Helping fall asleep.', false, NULL),
  
  -- Challenges & Trends
  ('viralchallenge', 'ViralChallenge', 'Spreading challenges.', false, NULL),
  ('dancetrend', 'DanceTrend', 'New dance moves.', false, NULL),
  ('grwm', 'GRWM', 'Get Ready With Me.', false, NULL),
  ('outfitcheck', 'OutfitCheck', 'Show your fit.', false, NULL),
  ('dayinmylife', 'DayInMyLife', 'Full day vlog.', false, NULL),
  ('transformationtuesday', 'TransformationTuesday', 'Before/after.', false, NULL)
ON CONFLICT (slug) DO NOTHING;

