-- =============================================
-- ADD TECHNOLOGY, HEALTH, SPORTS, ENTERTAINMENT & DEEP NICHE TOPICS
-- Final expansion to reach 4,000+ topics covering every major category and sub-niche
-- =============================================

INSERT INTO public.topics (slug, label, description, is_featured, created_by)
VALUES
  -- Technology Deep Dive
  ('quantumcomputing', 'QuantumComputing', 'Next-level super fast computers.', false, NULL),
  ('robotics', 'Robotics', 'Building and programming robots.', false, NULL),
  ('drone', 'Drone', 'Flying cameras and delivery bots.', false, NULL),
  ('smarthome', 'SmartHome', 'Connected house devices.', false, NULL),
  ('homeautomation', 'HomeAutomation', 'Automatic lights, locks, thermostats.', false, NULL),
  ('wearables', 'Wearables', 'Smartwatches and fitness trackers.', false, NULL),
  ('applewatch', 'AppleWatch', 'Apple''s wrist computer.', false, NULL),
  ('samsunggalaxy', 'SamsungGalaxy', 'Samsung phones and ecosystem.', false, NULL),
  ('oneplus', 'OnePlus', 'High-spec Android phones.', false, NULL),
  ('pixel', 'Pixel', 'Google''s pure Android phones.', false, NULL),
  ('cyberpunk', 'Cyberpunk', 'Futuristic neon tech aesthetic.', false, NULL),
  ('hackathon', 'Hackathon', 'Coding competitions.', false, NULL),
  ('opensource', 'OpenSource', 'Free and editable software.', false, NULL),
  ('github', 'GitHub', 'Code sharing platform.', false, NULL),
  ('devops', 'DevOps', 'Development + operations.', false, NULL),
  ('fullstackdeveloper', 'FullStackDeveloper', 'Front and back-end coder.', false, NULL),
  ('frontend', 'Frontend', 'User-facing code.', false, NULL),
  ('backend', 'Backend', 'Server-side code.', false, NULL),
  ('uiux', 'UIUX', 'User interface and experience design.', false, NULL),
  ('figma', 'Figma', 'Design tool.', false, NULL),
  ('adobexd', 'AdobeXD', 'Another design tool.', false, NULL),
  ('nocode', 'NoCode', 'Build apps without coding.', false, NULL),
  ('bubble', 'Bubble', 'Popular no-code platform.', false, NULL),
  ('webflow', 'Webflow', 'No-code websites.', false, NULL),
  ('flutter', 'Flutter', 'Google''s app framework.', false, NULL),
  ('reactnative', 'ReactNative', 'Facebook''s mobile app framework.', false, NULL),
  ('swift', 'Swift', 'Apple app language.', false, NULL),
  ('kotlin', 'Kotlin', 'Modern Android language.', false, NULL),
  
  -- Health & Wellness Deep
  ('biohacking', 'Biohacking', 'Optimizing your body and mind.', false, NULL),
  ('longevity', 'Longevity', 'Living longer and healthier.', false, NULL),
  ('intermittentfasting', 'IntermittentFasting', 'Eating windows for health.', false, NULL),
  ('coldplunge', 'ColdPlunge', 'Ice baths for recovery.', false, NULL),
  ('sauna', 'Sauna', 'Heat therapy.', false, NULL),
  ('redlighttherapy', 'RedLightTherapy', 'Skin and recovery light.', false, NULL),
  ('nootropics', 'Nootropics', 'Brain-boosting supplements.', false, NULL),
  ('sleepoptimization', 'SleepOptimization', 'Better sleep hacks.', false, NULL),
  ('guthealth', 'GutHealth', 'Microbiome and digestion.', false, NULL),
  ('functionalmedicine', 'FunctionalMedicine', 'Root-cause health.', false, NULL),
  ('ayurveda', 'Ayurveda', 'Ancient Indian medicine.', false, NULL),
  ('tcm', 'TCM', 'Traditional Chinese Medicine.', false, NULL),
  ('herbalremedies', 'HerbalRemedies', 'Plant-based healing.', false, NULL),
  ('essentialoils', 'EssentialOils', 'Aromatherapy oils.', false, NULL),
  
  -- Sports Deep
  ('soccer', 'Soccer', 'World''s most popular sport.', false, NULL),
  ('football', 'Football', 'American NFL.', false, NULL),
  ('basketball', 'Basketball', 'NBA and streetball.', false, NULL),
  ('baseball', 'Baseball', 'MLB and little league.', false, NULL),
  ('cricket', 'Cricket', 'Huge in India, UK, Australia.', false, NULL),
  ('rugby', 'Rugby', 'Tough contact sport.', false, NULL),
  ('tennis', 'Tennis', 'Grand slams and pros.', false, NULL),
  ('golf', 'Golf', 'Precision club sport.', false, NULL),
  ('formula1', 'Formula1', 'F1 racing.', false, NULL),
  ('motogp', 'MotoGP', 'Motorcycle racing.', false, NULL),
  ('boxing', 'Boxing', 'Punching sport.', false, NULL),
  ('mma', 'MMA', 'Mixed martial arts.', false, NULL),
  ('ufc', 'UFC', 'Biggest MMA organization.', false, NULL),
  ('wrestling', 'Wrestling', 'WWE entertainment.', false, NULL),
  ('olympics2024', 'Olympics2024', 'Paris games (still trending into 2025).', false, NULL),
  ('paralympics', 'Paralympics', 'Adaptive sports.', false, NULL),
  ('surfing', 'Surfing', 'Wave riding.', false, NULL),
  ('skateboarding', 'Skateboarding', 'Street and park.', false, NULL),
  ('snowboarding', 'Snowboarding', 'Winter slopes.', false, NULL),
  ('extremesports', 'ExtremeSports', 'Skydiving, base jumping.', false, NULL),
  
  -- Movies, TV & Entertainment
  ('netflixseries', 'NetflixSeries', 'Shows on Netflix.', false, NULL),
  ('disneyplus', 'DisneyPlus', 'Disney and Marvel content.', false, NULL),
  ('hulu', 'Hulu', 'American streaming.', false, NULL),
  ('primevideo', 'PrimeVideo', 'Amazon''s platform.', false, NULL),
  ('hbomax', 'HBOMax', 'Premium series (now Max).', false, NULL),
  ('moviereview', 'MovieReview', 'Honest film opinions.', false, NULL),
  ('spoilerfree', 'SpoilerFree', 'No-plot-giveaway reviews.', false, NULL),
  ('oscars', 'Oscars', 'Academy Awards.', false, NULL),
  ('superheromovies', 'SuperheroMovies', 'Marvel/DC films.', false, NULL),
  ('horrormovies', 'HorrorMovies', 'Scary flicks.', false, NULL),
  ('romcom', 'RomCom', 'Romantic comedies.', false, NULL),
  ('animeseries', 'AnimeSeries', 'Japanese animated shows.', false, NULL),
  ('kdramaaddict', 'KDramaAddict', 'Korean dramas.', false, NULL),
  ('bollywoodmovies', 'BollywoodMovies', 'Indian cinema.', false, NULL),
  
  -- Education & Skills
  ('learntocode', 'LearnToCode', 'Start programming.', false, NULL),
  ('languagelearning', 'LanguageLearning', 'New languages.', false, NULL),
  ('duolingo', 'Duolingo', 'Popular language app.', false, NULL),
  ('spanishlearning', 'SpanishLearning', 'Learning Spanish.', false, NULL),
  ('french', 'French', 'French language.', false, NULL),
  ('japaneselearning', 'JapaneseLearning', 'Nihongo.', false, NULL),
  ('onlinecourses', 'OnlineCourses', 'Digital classes.', false, NULL),
  ('coursera', 'Coursera', 'University courses.', false, NULL),
  ('udemy', 'Udemy', 'Affordable skills courses.', false, NULL),
  ('masterclass', 'MasterClass', 'Celebrity-taught classes.', false, NULL),
  ('productivitytools', 'ProductivityTools', 'Apps that save time.', false, NULL),
  ('notion', 'Notion', 'All-in-one workspace.', false, NULL),
  ('obsidian', 'Obsidian', 'Note-taking with links.', false, NULL),
  ('anki', 'Anki', 'Flashcard spaced repetition.', false, NULL),
  
  -- Personal Finance Deep
  ('budgeting', 'Budgeting', 'Tracking money.', false, NULL),
  ('frugalliving', 'FrugalLiving', 'Saving smart.', false, NULL),
  ('minimalistlifestyle', 'MinimalistLifestyle', 'Own less, live more.', false, NULL),
  ('creditscore', 'CreditScore', 'Building good credit.', false, NULL),
  ('debtfreejourney', 'DebtFreeJourney', 'Paying off debt.', false, NULL),
  ('earlyretirement', 'EarlyRetirement', 'Retire before 65.', false, NULL),
  ('indexfunds', 'IndexFunds', 'Passive stock investing.', false, NULL),
  ('rothira', 'RothIRA', 'Tax-free retirement account.', false, NULL),
  ('401k', '401k', 'Employer retirement plan.', false, NULL),
  
  -- Home & Gardening
  ('indoorplants', 'IndoorPlants', 'Houseplants.', false, NULL),
  ('succulentlove', 'SucculentLove', 'Easy-care plants.', false, NULL),
  ('vegetablegarden', 'VegetableGarden', 'Grow your own food.', false, NULL),
  ('hydroponics', 'Hydroponics', 'Soil-less growing.', false, NULL),
  ('composting', 'Composting', 'Turn waste into soil.', false, NULL),
  ('tinyhouse', 'TinyHouse', 'Small efficient homes.', false, NULL),
  ('homegym', 'HomeGym', 'Workout space at home.', false, NULL),
  ('kitchenremodel', 'KitchenRemodel', 'Upgrading cooking area.', false, NULL),
  
  -- Fashion Sub-Styles Deep
  ('streetwear', 'Streetwear', 'Hypebeast culture.', false, NULL),
  ('hypebeast', 'Hypebeast', 'Limited-edition drops.', false, NULL),
  ('sneakerhead', 'SneakerHead', 'Shoe collectors.', false, NULL),
  ('vintageclothing', 'VintageClothing', 'Second-hand gems.', false, NULL),
  ('sustainablefashion', 'SustainableFashion', 'Eco-friendly clothes.', false, NULL),
  ('athleisure', 'Athleisure', 'Gym clothes as daily wear.', false, NULL),
  ('gothfashion', 'GothFashion', 'Dark aesthetic.', false, NULL),
  ('preppystyle', 'PreppyStyle', 'Clean collegiate look.', false, NULL),
  ('egirl', 'Egirl', 'Internet girl aesthetic.', false, NULL),
  ('eboy', 'Eboy', 'Internet boy aesthetic.', false, NULL),
  
  -- Beauty & Hair Deep
  ('haircolor', 'HairColor', 'Dying and highlights.', false, NULL),
  ('balayage', 'Balayage', 'Hand-painted highlights.', false, NULL),
  ('curlyhair', 'CurlyHair', 'Natural curls care.', false, NULL),
  ('naturalhair', 'NaturalHair', 'Black hair movement.', false, NULL),
  ('braids', 'Braids', 'Protective styles.', false, NULL),
  ('hairgrowth', 'HairGrowth', 'Longer stronger hair.', false, NULL),
  ('lashextensions', 'LashExtensions', 'Fake lashes.', false, NULL),
  ('microblading', 'Microblading', 'Semi-permanent brows.', false, NULL),
  
  -- Tattoos & Body Art
  ('tattooartist', 'TattooArtist', 'Ink professionals.', false, NULL),
  ('tattooideas', 'TattooIdeas', 'Inspiration designs.', false, NULL),
  ('minimaltattoo', 'MinimalTattoo', 'Small simple ink.', false, NULL),
  ('sleevetattoo', 'SleeveTattoo', 'Full arm coverage.', false, NULL),
  ('piercing', 'Piercing', 'Body jewelry.', false, NULL),
  
  -- Spirituality & Mindfulness
  ('manifestation', 'Manifestation', 'Attracting what you want.', false, NULL),
  ('lawofattraction', 'LawOfAttraction', 'Like attracts like.', false, NULL),
  ('crystalshealing', 'CrystalsHealing', 'Gemstone energy.', false, NULL),
  ('tarotreading', 'TarotReading', 'Card divination.', false, NULL),
  ('astrologysigns', 'AstrologySigns', 'Zodiac deep dives.', false, NULL),
  ('meditationmusic', 'MeditationMusic', 'Calming sounds.', false, NULL),
  ('chakras', 'Chakras', 'Energy centers.', false, NULL),
  
  -- Viral Trends & Challenges (2024–2025)
  ('booktoktrends', 'BookTokTrends', 'Current reading challenges.', false, NULL),
  ('cleantok', 'CleanTok', 'Cleaning hacks.', false, NULL),
  ('homeedit', 'HomeEdit', 'Organizing content.', false, NULL),
  ('gymtok', 'GymTok', 'Fitness trends.', false, NULL),
  ('foodtok', 'FoodTok', 'Recipe videos.', false, NULL),
  ('ootdtok', 'OOTDTok', 'Outfit videos.', false, NULL),
  ('couplegoalschallenge', 'CoupleGoalsChallenge', 'Relationship trends.', false, NULL),
  ('dancechallenge2025', 'DanceChallenge2025', 'New moves.', false, NULL)
ON CONFLICT (slug) DO NOTHING;

